import type { Category, LinkItem } from './types';
import { Brush, Code, Zap, Layers, Folder, Star, BookOpen } from 'lucide-react';
import placeholderData from './placeholder-images.json';

export const initialCategories: Category[] = [
  { id: 'all', name: 'All Links', icon: Layers },
  { id: 'ui-ux', name: 'UI/UX', icon: Brush },
  { id: 'development', name: 'Development', icon: Code },
  { id: 'productivity', name: 'Productivity', icon: Zap },
  { id: 'resources', name: 'Resources', icon: Folder },
  { id: 'favorites', name: 'Favorites', icon: Star },
  { id: 'reading-list', name: 'Reading List', icon: BookOpen },
];

export const initialLinks: LinkItem[] = [
  {
    id: '1',
    url: 'https://react.dev/',
    title: 'React Official Website',
    description: 'The library for web and native user interfaces.',
    category: 'Development',
    tags: ['React', 'JavaScript', 'UI'],
    notes: 'The new docs are great. Need to check out the section on Concurrent Rendering.',
    createdAt: '2023-10-26T10:00:00Z',
    image: placeholderData.placeholderImages[0],
  },
  {
    id: '2',
    url: 'https://tailwindcss.com/',
    title: 'Tailwind CSS',
    description: 'A utility-first CSS framework for rapid UI development.',
    category: 'Development',
    tags: ['CSS', 'Framework', 'Design System'],
    notes: 'Using this for the LinkVault project. The JIT compiler is a game changer.',
    createdAt: '2023-10-25T14:30:00Z',
    image: placeholderData.placeholderImages[1],
  },
  {
    id: '3',
    url: 'https://www.figma.com/',
    title: 'Figma',
    description: 'The collaborative interface design tool.',
    category: 'UI/UX',
    tags: ['Design', 'UI', 'UX', 'Collaboration'],
    notes: 'All mockups for LinkVault are designed in Figma. Remember to organize the components library.',
    createdAt: '2023-10-24T11:20:00Z',
    image: placeholderData.placeholderImages[2],
  },
  {
    id: '4',
    url: 'https://www.notion.so/',
    title: 'Notion',
    description: 'The all-in-one workspace for your notes, tasks, wikis, and databases.',
    category: 'Productivity',
    tags: ['Notes', 'Productivity', 'Organization'],
    notes: 'Great for project management and keeping track of personal goals.',
    createdAt: '2023-10-23T09:05:00Z',
    image: placeholderData.placeholderImages[3],
  },
  {
    id: '5',
    url: 'https://nextjs.org/docs',
    title: 'Next.js Documentation',
    description: 'The React Framework for the Web. Full-stack capabilities.',
    category: 'Development',
    tags: ['Next.js', 'React', 'Framework', 'SSR'],
    notes: 'Key features to explore: App Router, Server Actions, and integrated TypeScript support.',
    createdAt: '2023-10-22T18:45:00Z',
    image: placeholderData.placeholderImages[4],
  },
  {
    id: '6',
    url: 'https://dribbble.com/',
    title: 'Dribbble',
    description: 'Discover the world’s top designers & creative professionals.',
    category: 'UI/UX',
    tags: ['Inspiration', 'Design', 'UI'],
    notes: 'A go-to for visual inspiration when starting a new UI project.',
    createdAt: '2023-10-21T16:00:00Z',
    image: placeholderData.placeholderImages[5],
  },
  {
    id: '7',
    url: 'https://genkit.dev/',
    title: 'Genkit AI',
    description: 'The open source framework for building production-ready AI-powered apps.',
    category: 'Development',
    tags: ['AI', 'TypeScript', 'Firebase'],
    notes: 'Using Genkit for the AI search feature in LinkVault. The flow-based paradigm is very intuitive.',
    createdAt: '2023-10-28T12:00:00Z',
    image: placeholderData.placeholderImages[6],
  },
  {
    id: '8',
    url: 'https://developer.mozilla.org/en-US/',
    title: 'MDN Web Docs',
    description: 'The ultimate resource for web developers, maintained by Mozilla and individual contributors.',
    category: 'Resources',
    tags: ['JavaScript', 'CSS', 'HTML', 'Documentation'],
    notes: 'The most reliable source for web standards documentation.',
    createdAt: '2023-10-20T09:30:00Z',
    image: placeholderData.placeholderImages[7],
  },
];
